project:
  type: book

book:
  title: "Big Book of Python"
  author: "The Community"
  date: "2021-12-27"
  chapters:
    - index.qmd
    - install.qmd
    - packaging.qmd
    - data_science.qmd
    - domain_specific.qmd
    - programming.qmd
    - web.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreport

website:
  google-analytics: "G-9V0PHPJJY9"

